components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
          required: true
          example: test
        displayName:
          type: string
          required: true
          example: test

/user:
  get:
    tags:
      - User
    summary: Get an users list
    produce:
      - application/json
    parameters:
      - name: username
        in: query
      - name: displayname
        in: query
    responses:
      '200': 
        description: Success
        content:
          application/json:
            type: object
            properties:
              username:
                type: string
              displayName:
                type: String
      '404':
        description: Not found

  post:
  tags:
      - User
    summary: Add a new user from body data
    requestBody:
      required: true
      icontent:
        application/json
    responses:
      '204':
        description: No content
      '400':
        description: Error